# troys top 10 movies
def movies():
    print("1. The Godfather")
    print()
    print("2. Goodfellas")
    print()
    print("3. The Wolf Of Wall Street")
    print()
    print("4. The Irishman")
    print()
    print("5. The Social Network")
    print()
    print("6. Scarface")
    print()
    print("7. Catch me if you Can")
    print()
    print("8. The Dark Knight")
    print()
    print("9. Into the Spider Verse")
    print()
    print("10. Baby Driver")
    print()

asdf = input()
movies()